# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # Define specific supported pairs to avoid invalid combinations
        include:
          - {os: linux,   arch: amd64, name: linux-x64}
          - {os: linux,   arch: arm64,   name: linux-arm64}
          - {os: linux,   arch: 386,   name: linux-x86}
          - {os: windows, arch: amd64, name: windows-x64}
          - {os: windows, arch: arm64,   name: windows-arm64}
          - {os: windows, arch: 386,   name: windows-x86}
          - {os: darwin,  arch: amd64, name: macos-amd64}
          - {os: darwin,  arch: arm64, name: macos-arm64}
          - {os: darwin,  arch: 386, name: macos-x86}

        go:
          - '1.26.1' # minimum version
          - 'oldstable'
          - 'stable'
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: |
        go get ./...
        go install .
        go build -v ./...
      env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

    - name: Test
      env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
      run: go test -v ./...
